version: "3"
services:
  ipfs:
    container_name: "ipfs"
    expose:
      - 4001
      - 8080
    ports:
      - 4001:4001
      - 5001:5001
      - 8090:8090
    image: ipfs/go-ipfs
    volumes:
      - ./data:/data/ipfs/
    command: --routing=dhtclient --enable-gc
    restart: always

  dcs:
    build: .
    container_name: dcs
    volumes:
      - ./data:/opt/dcs/data
      - ./log:/opt/dcs/log
    working_dir: /opt/dcs
    command: npm start
    links:
      - ipfs
    depends_on:
      - ipfs
    restart: always

